### PR TITLE
Add autocomplete functionnality

### LINKED ISSUE #98: Add slash command autocomplete functionality
From 5.24 MM server has a slash command autocomplete functionality feature. An API can be found [here](https://github.com/mattermost/mattermost-server/blob/master/model/command_autocomplete.go#L28)
To implement the feature add `AutocompleteData` struct to the `Command` when registering a slash command.

Similar PRs:
For Todo plugin https://github.com/mattermost/mattermost-plugin-todo/pull/69
For Agenda plugin https://github.com/mattermost/mattermost-plugin-agenda/pull/40

### PR DESCRIPTION
**Pull request by nathanaelhoun**
#### Summary

- [x] Add slash autocomplete functionnality

#### Ticket Link

Closes #98

### CODE REVIEW

**Comment by hanzei** [comment]
@nathanaelhoun You did run into a bug fixed by https://github.com/mattermost/mattermost-server/pull/14692. Could you please try if using `master` of `mattermost-server` fixes that issue?

**Comment by nathanaelhoun** [comment]
Thanks for the clue @hanzei. Using latest master revelead my error: adding a subcommand and a text argument is not allowed.

So I have a problem with `/jitsi [topic]` and `/jitsi settings` (to get settings).

How about renaming these commands to `/jitsi start [topic]` and `/jitsi get_settings` ?

**Comment by jespino** [comment]
@nathanaelhoun By the way, there is no way to properly localize the autocomplete from the user language perspective, we could make it localizable based on server side language, but I think is better to wait until the autocomplete support proper translations.

**Comment by nathanaelhoun** [comment]
Thanks for the response @jespino :-)

How can we handle the different subcommands and arguments (see my comment of yesterday)?

For example, `/jitsi` can be follow by a text argument for the `[topic]` or by a subcommand like `help` or `settings`.

**Comment by jespino** [comment]
Probably @iomodo knows better

**Comment by iomodo** [comment]
Hey @nathanaelhoun my suggestion would be to use `/jitsi start [topic]` and `/jitsi settings`.
With `/jitsi [topic]` you won't be able to distinguish between `settings` and starting new call.

**Comment by jespino** [comment]
@nathanaelhoun Because that is the current situation, I would prefer to keep it working as is now, and just remove the `[topic]` option from the autocomplete, you still can see that in the help (and maybe in the description of the jitsi command). Is not shown in the autocompletion but is usable. And I see way more value in the `settings` and `help` autocompletion than in the `[topic]` one.

**Comment by nathanaelhoun** [comment]
Ok, I kept the current commands scheme, dropping the autocomplete for `/jitsi [topic]` and `/jitsi settings (nothing-here)`. Let me know if it seems go to you :eyes:

**Comment by jespino** [comment]
It is not working as I would expect. I would expect to get the suggestions, but at the same time allowing me to just execute `/jitsi settings` to see the current settings (now I have to trick the system pressing escape and then enter) and even worse, I can't execute a simple `/jitsi` command without parameters because it autocompletes to help option instead of executing the `/jitsi` command.

**Comment by nathanaelhoun** [comment]
Thanks for your feedback @jespino. 
I have a problem: I couldn't figure out how to add an "empty" autocomplete suggestion, i.e. for `/jitsi settings`, how to propose "" (to see the current settings) in addition to the the others suggestions (`embedded` and `naming_scheme`). 
We can't add a command with an empty trigger, and we can't mix subcommands and arguments for one command (both are refused by the server).

For the `/jitsi` problem, we can rename it to `/jitsi start [topic]` as suggested by @iomodo, but we'll still have the problem if we want to start a meeting without a topic.

I'll submit a commit to test with 
- `/jitsi [topic]` → `/jitsi start [topic]`
- `/jitsi settings` → `/jitsi settings see`
I'm still learning how to do CLI, thanks for your patience

**Comment by iomodo** [comment]
@jespino an empty subcommand is not allowed by design. If you want to finish your command early you have to hit `esc` and suggestions will go away. It might be confusing but that's how UX wanted it.

**Comment by jespino** [comment]
@iomodo then the UX has to be reviewed, that is broken behavior.

**Comment by nathanaelhoun** [comment]
So with the current autocomplete design, this seems to me to be a good compromise: 
- previous commands `/jitsi`, `/jitsi [topic]` and `/jitsi settings` commands are still working (as long as the `[topic]` is not "start") but are not suggested, 
- new commands `/jitsi start [topic]` and `/jitsi settings see` are suggested by autocomplete.

**Comment by jespino** [comment]
But to use the you have to press escape what is counterintuitive. I would rather prefer to not have autocompletion until the experience is correct, for me, at least it makes it less usable.

**Comment by nathanaelhoun** [comment]
Mattermost [5.26 improved the UI](https://docs.mattermost.com/administration/changelog.html#integrations) and we can execute a slash command without the "press escape" problem. Do you think this solve the problem @jespino ?

image

**Comment by jespino** [comment]
@nathanaelhoun yes, it solves it. Thanks! @larkox is now the main maintener, @larkox do you want to review this? or do you prefer me to review this?

**Review by larkox — APPROVED** [review]
LGTM! Thank you for the contribution!

**Review by hanzei — APPROVED** [review]
LGTM

**Review by DHaussermann — APPROVED** [review]
Tested and passed
- This is working as expected
- All commands have been added and are functional
- Tested in Browser, desktop and mobile
LGTM!

Huge thanks @nathanaelhoun for adding this. It makes a huge differnce on the UX!

Found a couple issues not introduced by this PR:
- https://github.com/mattermost/mattermost-plugin-jitsi/issues/154 (linting error)
- https://mattermost.atlassian.net/browse/MM-29274 (RN App has issue displaying subcommands for plugin)

**Pull request merged**
