### PR TITLE
Naming options

### PR DESCRIPTION
**Pull request by lediur**
PR builds off of https://github.com/seansackowitz/mattermost-plugin-jitsi/pull/26 (as the first squashed commit in this PR) and is inspired by https://github.com/seansackowitz/mattermost-plugin-jitsi/pull/21 as well.

This PR adds a settings option where the user can choose between different naming schemes:
    -   Randomly-generated English titlecase e.g. PlayfulDragonsObserveCuriously (similar to how meet.jit.si operates by default)
    -   Randomly-generated English kebabcase e.g. playful-dragons-observe-curiously
    -   Random UUID
    -   Random 10 digit code
    -   Random 10 letter code
    -   Your channel URL slug with no separators (e.g. `townsquare`)
    -   Your channel URL slug with dash separators (e.g. `town-square`)

### CODE REVIEW

**Comment by cekstam** [comment]
This looks awesome, any chance of getting it merged and released?

+1 from me.

**Comment by jespino** [comment]
I going to take a look into this

**Comment by jespino** [comment]
This is adding to many things in the same PR, I think I going to try to extract the different changes, like the naming part in one side, and the slash command in other side.

**Comment by lediur** [comment]
This was originally based on #26 so it does include several child PRs in it.

**Comment by hanzei** [comment]
@lediur @jespino With https://github.com/mattermost/mattermost-plugin-jitsi/pull/40  merged, is this PR valid any longer?

**Comment by lediur** [comment]
I don't think so, I'll close this PR.

**Pull request closed without merging**
