### PR TITLE
Bump version to 2.0.0

### PR DESCRIPTION
**Pull request by hanzei**

### CODE REVIEW

**Comment by hanzei** [comment]
@jespino @jasonblais Are there any outstanding changes that should go into this release? https://github.com/mattermost/mattermost-plugin-jitsi/pull/83?

**Comment by jasonblais** [comment]
@hanzei @jespino I would like to ship https://github.com/mattermost/mattermost-plugin-jitsi/pull/83 and https://github.com/mattermost/mattermost-plugin-jitsi/pull/104 with v2.0.0. Both are small changes.

At minimum https://github.com/mattermost/mattermost-plugin-jitsi/pull/83.

**Comment by jespino** [comment]
I would like to include a couple of other languages, but is not strickly needed.

I want to QA it a bit again before we release.

And there is a security issue to address before the 2.0.0

**Comment by hanzei** [comment]
> I would like to include a couple of other languages, but is not strickly needed.

I'm working on the german translation. Will put out a PR soon.

**Comment by jasonblais** [comment]
@jespino @hanzei looks like everything is now merged. Is this pending QA review?

**Comment by jespino** [comment]
@jasonblais Yes, I think so, we are almost there with the autocompletion of the slash command, but is not really needed for 2.0.0 (but is pretty cool)

**Comment by jespino** [comment]
@jasonblais and a small PR fixing a problem that @jupenur detected.

**Comment by jasonblais** [comment]
@jespino #119 is then the last PR before final QA testing, after which we can ship in the marketplace?

**Comment by jespino** [comment]
@jasonblais yes, it is waiting for a juho last review

**Comment by jasonblais** [comment]
Great! I've also reached out to Dylan for QA

**Comment by hanzei** [comment]
@DHaussermann This is ready for a final review

**Pull request merged**
