### PR TITLE
Add option to choose name generator

### LINKED ISSUE #22: meetingID is allways generateRoomWithoutSeparator
Many thanks for this plugin.

However, we had to realize that for each meeting a random name is generated. 
Is a special Mattermost version required to use the req.topic? Currently we are using version 5.8.0.

### PR DESCRIPTION
**Pull request by jespino**
This is heavily based on the changes proposed by @lediur in the PR #33 

Fixes #22

### CODE REVIEW

**Comment by rbdevr** [comment]
Hello all.

Is there a release date for this new version?

**Comment by jespino** [comment]
@rbdevr not yet, we have to make some changes, one of them is around improve the JWT data shown, and other is about reducing the number of namining generation options to only Random Names, UUID, and Context based (Channels would be [team-name]-[channel-name]-[random-10-chars], DMs and GMs would be the personal meeting [username]-[hash of user id]). Maybe we can preserve the 10 random chars/numbers for easy access from mobile.

**Comment by rbdevr** [comment]
sounds great. is all this development been done in a different channel?

**Comment by jespino** [comment]
@rbdevr what do you mean with different channel?

**Comment by rbdevr** [comment]
You have mentioned many features, I'm sure its being discussed somewhere else.

**Comment by jespino** [comment]
@rbdevr yes, part of this has been discussed as part of the PRs that were already there, but others has been in informal covnersations, and finally a lot of thinks just happened in my head, but if you want to suggest things, feel free to create issues here or join the "Plugin: Jitsi" channel in the https://community.mattermost.com

**Pull request merged**
