### PR TITLE
#152-Add autocomplete icon

### PR DESCRIPTION
**Pull request by tw-ayush**
A description of what this pull request does.
#152-Add autocomplete icon
add the icon data in response model

https://github.com/mattermost/mattermost-plugin-jitsi/issues/152

### CODE REVIEW

**Comment by tw-ayush** [comment]
@hanzei can you please share the link where I can get the steps for setting up and testing of the changes. (Mattermost server setup and plugin installation)

**Comment by tw-ayush** [comment]
@larkox can you add hacktoberfest tag to this PR if that works for you?

**Review by hanzei — CHANGES_REQUESTED** [review]
It seems like you got some unrelated changes from https://github.com/mattermost/mattermost-plugin-jitsi/pull/158 in this PR. Could you please remove them?

**Comment by hanzei** [comment]
@tw-ayush You can find the documentation for the setup at https://developers.mattermost.com/extend/plugins/developer-setup/

**Comment by tw-ayush** [comment]
> It seems like you got some unrelated changes from #158 in this PR. Could you please remove them?

Please check now

**Comment by tw-ayush** [comment]
> @tw-ayush You can find the documentation for the setup at https://developers.mattermost.com/extend/plugins/developer-setup/

i followed all the steps, tried multiple times but it does not work for me 😢

**Review by larkox — APPROVED** [review]
Thanks for the contribution. Apart of the changes proposed by @hanzei, it looks good to me.

**Review by hanzei — APPROVED** [review]
LGTM :+1:

**Review by larkox — APPROVED** [review]

**Comment by hanzei** [comment]
Tested locally. Jitsi icon is shown for slash command responses. It looks good on a dark and bright theme.

**Pull request merged**
