### PR TITLE
Cherry-pick (#214) into release-2.0

### PR DESCRIPTION
**Pull request by agarciamontoro**
#### Summary
The `release-2.0` branch has been created from the `v2.0.0` tag. This PR cherry-picks #214 into that branch, so we can release a new v2.1.0 with only this change.

#### Ticket Link
--

### CODE REVIEW

**Comment by DHaussermann** [comment]
@agarciamontoro I'm struggling to build this PR branch. 
with node 13 I get an error.
image

With node 16 npm fetch never seems to end. 
 
Can you provide a build or some troubleshooting ideas? :)
 Maybe the node and npm version you are using to build this or a way to make circle CI build it.

**Review by larkox — APPROVED** [review]
LGTM, just a question to improve my knowledge.

**Review by iomodo — APPROVED** [review]

**Comment by agarciamontoro** [comment]
@DHaussermann, build is also failing on CI. Let me check :pray:

**Comment by mickmister** [comment]
Closing per https://community-daily.mattermost.com/core/pl/cix75ceit3neff7fgacyoo7uth, with the follow up being to release a new version off of master

**Pull request closed without merging**
