### PR TITLE
Reducing the number of options for naming

### LINKED ISSUE #45: Proposal: Meeting naming schema
Currently, we have the following meeting naming options:

1. english-titlecase
2. english-kebabcase
3. uuid
4. digits
5. letters
6. teamchannel
7. teamchannel-salt

Following [Hick's Law](https://en.wikipedia.org/wiki/Hick%27s_law), we aim to [limit the number of choices to 3 or 4](https://docs.mattermost.com/developer/fx-guidelines.html#display-number-of-choices). I would like to apply this law for the meeting naming option as well.

Specifically, limit the options to
- english-titlecase makes sense given that is the default naming convention for Jitsi meetings. 
- uuid supports uniqueness, which is particularly important when using the public Jitsi service

An additional consideration is
- teamchannel suggested by @rbdevr or a mattermost-style naming convention that uses a combination of teams and channels (see below)

https://github.com/mattermost/mattermost-plugin-jitsi/pull/42/files#r428284593

### PR DESCRIPTION
**Pull request by jespino**
I reduced the number of options, and added a special one for "context based".

Fixes #45

### CODE REVIEW

**Comment by jespino** [comment]
@jasonblais can you review this, probably the description can be way better than my proposal. I kept the 10 digits options to have short ids easy sharing to mobile or things like that.

**Comment by jasonblais** [comment]
@jespino Thanks! I'm thinking about how to simplify the description - it might make sense to move the details into the setting help text instead of in the option description.

Questions:
1. For the mattermost style meeting name - are we adding a random text to prevent conflicts? Would you have an example of a meeting name with team=DevOps and channel=Incidents?
2. "I kept the 10 digits options to have short ids easy sharing to mobile or things like that." - Interesting. Can you help share more how the shorter id will make it easier to share on mobile?

**Comment by jasonblais** [comment]
Here's one suggestion - I feel it could be more concise, so definitely open to feedback. Slightly updated the other value descriptions for clarity.

```
                "key": "JitsiNamingScheme",

                "display_name": “Jitsi Meeting Names”,

                "type": "radio",

                "help_text": “Select how meeting names are generated.”,

                "default": "english-titlecase",

                "options": [

                    {

                        "display_name": “Random English words in title case (e.g. PlayfulDragonsObserveCuriously)",

                        "value": "english-titlecase"

                    },

                    {

                        "display_name": "UUID (universally unique identifier)”,

                        "value": "uuid"

                    },
                    {
                        "display_name": “Mattermost context specific names. Combination of team name, channel name and random text in public and private channels; personal meeting name in direct and group messages channels.”,
                        "value": "mattermost"
                    },

                    {

                        "display_name": “Random ten-digit number. Not recommended if you use a public server such as meet.jit.si as this option can lead to a naming conflict.”,

                        "value": "digits"

                    }
```

**Comment by jespino** [comment]
@jasonblais about your questions:

1. Yes, the idea is to avoid collisions in the same server, for example if two people wants to create a videoconference in the same channel at the same time for two different purposes, having this extra text at the end, avoids collitions, and you can use a public instance of jitsi like `meet.jit.si`.
2. I'm not sure if that scenario even happens, but I can send you the link to the meeting, and for some reason (I can't use from my laptop, or I prefer to use the mobile app, I have to copy the room name, and if this is a 10 numbers, is really easy to write it in the mobile app, with a uuid or something like that, is really hard).

**Comment by jasonblais** [comment]
@jespino 
1. That makes sense :+1:
2. In this use case, would you have received the link to the meeting to your phone? If so, would you be able to copy-paste the room name via your phone?

**Comment by jespino** [comment]
@jasonblais maybe yes, maybe not, It depends, I found myself following exactly the workflow proposed with zoom meetings, so... I don't think is an alien use case. But I'm ok of removing it and wait until somebody request that feature.

**Comment by jasonblais** [comment]
@jespino Ah I see. One reason I hesitate is that it is an edge case, so by default an admin will likely choose one of the other three options (English words, UUID, Mattermost style).  So in that way I lean towards removing it until we hear people asking for the option.

**Comment by jespino** [comment]
@jasonblais ok, lets remove it then for now.

**Comment by jespino** [comment]
@jasonblais done, PTAL

**Pull request merged**
