### PR TITLE
Translations update from Mattermost Weblate

### PR DESCRIPTION
**Pull request by weblate**
Translations update from [Mattermost Weblate](https://translate.mattermost.com) for [Mattermost Plugins/Mattermost Jitsi Plugin - Server 2](https://translate.mattermost.com/projects/mattermost-plugins/mattermost-jitsi-plugin-server-2/).

Current translation status:

Weblate translation status

### CODE REVIEW

**Review by larkox — APPROVED** [review]

**Comment by larkox** [comment]
@hanzei The format changed a lot, so not sure if these changes are supposed to go in.

I checked the translations, and nothing seems out of place (a few lines do not appear formatted on github, not sure why, but they seem ok), therefore I approved, but wanted a second opinion on the format.

**Comment by mickmister** [comment]
@jespino Do you have any thoughts on the change in data structure for the i18n configs?

**Comment by jespino** [comment]
Nope, this should be something related to the weblate translations format during the export for the generation, maybe @metanerd knows more about that.

**Comment by metanerd** [comment]
I don't know more unfortunately. PR looks fine to me though. If Weblate now wants it that way, so be it, I guess.

**Review by hanzei — CHANGES_REQUESTED** [review]
The file format proposed in this PR is the one from `https://github.com/nicksnyder/go-i18n`. Given that the plugin code expects the `https://github.com/nicksnyder/go-i18n/v2` format this PR will break translations. 

Weblate needs to get patched to support `v2` format: https://github.com/WeblateOrg/weblate/issues/4323

**Comment by lieut-data** [comment]
Weblate is no longer maintaining these.

**Pull request closed without merging**
