### PR TITLE
Use UUID instead of random generated room's name

### PR DESCRIPTION
**Pull request by robyf70**
I've just made this PR to use UUID instead of random generated room's name

### CODE REVIEW

**Comment by seansackowitz** [comment]
Hey @robyf70 This looks good, however, if you could make this as a toggle-able option in the settings, that would be awesome. I am getting requests for different room name generation types, so being able to switch between different types would be more widely useful.

**Comment by robyf70** [comment]
@seansackowitz Thanks! However this my very first go&mattermost PR. I did it because I've installed ``mattermost`` and I was looking how to generate random and meaningless room names. I'm totally new on ``mattermost`` plugin development. Anyway, I would propose to make it as selectable options in order to have multiple options to choose, but I cannot have much time right now to improve my PR, sorry for that.

**Comment by rbdevr** [comment]
Good day @robyf70.

The current plugin adds some settings in MM system console.

 I'm sure you can copy the feature and use to make a "Use random names/ Use channel names" switch.

**Comment by robyf70** [comment]
Hi @rbdevr,

Very good! I really like the JWT merge! I will have a look a the MM selector and I will review this PR.

**Comment by robyf70** [comment]
@rbdevr The PR should be ok now

**Comment by hanzei** [comment]
@robyf70  @jespino With https://github.com/mattermost/mattermost-plugin-jitsi/pull/40  merged, is this PR valid any longer?

**Comment by robyf70** [comment]
@hanzei Looking at the #40 I guess we can close this PR

**Comment by hanzei** [comment]
Then I'm going to close it. Still, thanks for the contribution and your time!

**Pull request closed without merging**
