### PR TITLE
gh-165

### PR DESCRIPTION
**Pull request by maisnamrajusingh**
#### Summary
fixes the spacing issue 
Screenshot 2021-06-15 at 4 50 46 PM
#### Ticket Link
Fixes https://github.com/mattermost/mattermost-plugin-jitsi/issues/165

### CODE REVIEW

**Review by larkox — APPROVED** [review]
Apart of the linting issues, LGTM.

**Review by hanzei — APPROVED** [review]
LGTM

**Comment by jasonblais** [comment]
@hanzei I think for these PRs we agreed QA testing happens prior to cutting a release, to make the QA load lighter?

**Comment by hanzei** [comment]
If @DHaussermann agrees with that, I'm fine with merging the PR without QA testing.

**Comment by jasonblais** [comment]
Yes, that is what we agreed on the call with Demansol last week, but I can confirm with Dylan as well

**Review by DHaussermann — APPROVED** [review]
Yes, let's merge this. 
I will regression test before the next Jitsi release. 

Thanks @maisnamrajusingh for this contribution.

**Pull request merged**
