### PR TITLE
#160 Meeting announcement created from ephemeral to get posted in RHS

### PR DESCRIPTION
**Pull request by tw-ayush**
Command responses don't get posted in the RHS #153
Added meeting if from Context (request) to the startMeeting

### CODE REVIEW

**Comment by tw-ayush** [comment]
Hey is there a way to add test for ServeHTTP methods??

**Comment by larkox** [comment]
Hi @tw-ayush , I am not sure how this change the behaviour to add the meeting in the right place. Care to explain?

Regarding adding tests, feel free to open a PR to add the tests needed, or just add them in this PR if you think they are relevant to this change.

**Comment by tw-ayush** [comment]
> Hi @tw-ayush , I am not sure how this change the behaviour to add the meeting in the right place. Care to explain?
> 
> Regarding adding tests, feel free to open a PR to add the tests needed, or just add them in this PR if you think they are relevant to this change.

hey apologies for the incorrect code earlier, this Issue has been a bit of a confusing pease of work for me.
Check if the changes are correct now.

**Comment by larkox** [comment]
The idea is good, but you need to somehow add the information in the StartMeetingFromAction structure. Probably the best place is to add the rootID to the context of the actions declared in "askMeetingType".

**Comment by tw-ayush** [comment]
> The idea is good, but you need to somehow add the information in the StartMeetingFromAction structure. Probably the best place is to add the rootID to the context of the actions declared in "askMeetingType".

I've added this change in the PR, do i also need to add this in request from someplace in the Repo ??

**Comment by larkox** [comment]
I'm not sure what you mean. Could you please elaborate?

**Comment by tw-ayush** [comment]
> I'm not sure what you mean. Could you please elaborate?

I've used the RootId from request context but haven't made any changes in the code base to add it there. Is there anyplace where i need to add this rootId in request data?

**Comment by larkox** [comment]
You would need to add the rootid in `server/plugin.go`, in the function askMeetingType, in the context of every action that needs it (I think all of them).

**Comment by tw-ayush** [comment]
> You would need to add the rootid in `server/plugin.go`, in the function askMeetingType, in the context of every action that needs it (I think all of them).

that's already been done in another ticket.

**Comment by larkox** [comment]
@tw-ayush Are you still working on this?

**Comment by tw-ayush** [comment]
> @tw-ayush Are you still working on this?

this was pending for merge.. Changes are there.
Or maybe i'm missing the context here..

**Review by hanzei — APPROVED** [review]
Tested locally and works as expected.

Typing the slash command in the RHS open the meeting there. Clicking the channel header button does open it in the central channel, which is fine as it's not obvious for the user that the RHS will be used.

@larkox Would you please take another look?

**Review by larkox — APPROVED** [review]

**Comment by hanzei** [comment]
@dipak-demansol Could you please review this PR?

**Review by dipak-demansol — APPROVED** [review]
LGTM

**Pull request merged**
