### PR TITLE
Add Czech

### PR DESCRIPTION
**Pull request by hason**
#### Summary
Add Czech translations

### CODE REVIEW

**Review by larkox — APPROVED** [review]
LGTM. Thanks!

**Review by jespino — APPROVED** [review]
LGTM

**Comment by hanzei** [comment]
@DHaussermann Are you fine with merging this PR without QA review?

**Review by DHaussermann — APPROVED** [review]
Sorry for the delay. Yes we're fine to merge this. 

Huge thanks @hason for this contribution 🎉  Much Appreciated!

@hanzei  please merge.

**Comment by DHaussermann** [comment]
@hanzei  or @jespino I notice I cannot adjust labels in this repo. Is this something one of you can grant?

**Pull request merged**
